// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huotxwjeyurmevkvljxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1b3R4d2pleXVybWV2a3Zsanh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTEwMDIsImV4cCI6MjA1OTg2NzAwMn0.7TLLztl6x8DrqhvoD48CercuNte-saJm0Yr8sP9FCbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);